### ISSUE TITLE
Java Sample code for "getting started with SDK's" is returning a 400 error in DefaultTokenProvider

### ISSUE THREAD

**Issue by dsbanks99** [ibm-cloud-docs/cloud-object-storage#130]
I'm trying the Java sample code at https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-sdk-gs&code=java as a way of getting started with COS.

I've replaced _endpoint, api-key, resource-instance-id_ with the values from my Credentials page. I've tried different values for _storage-class_ such as 'us-east'.

Whether I try client's createBucket or listBuckets example, I get the same error:

Exception in thread "main" com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: Token retrieval from IAM service failed (Service: IAM; Status Code: 400; Error Code: null; Request ID: null), S3 Extended Request ID: null
	at com.ibm.cloud.objectstorage.oauth.DefaultTokenProvider.retrieveToken(DefaultTokenProvider.java:160)
	at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.retrieveToken(DefaultTokenManager.java:381)
	at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.getToken(DefaultTokenManager.java:200)
	at com.ibm.cloud.objectstorage.oauth.IBMOAuthSigner.sign(IBMOAuthSigner.java:64)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1271)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4074)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4021)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:996)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:931)

The 400 error suggests a 'bad request'. What's bad about it?

**Comment by dsbanks99** [comment]
This can be closed, but maybe a note in the sample code would help. For me, I needed to change the SDKGlobalConfiguration.IAM_ENDPOINT to https://iam.test.cloud.ibm.com/identity/token  (adding the .test in the URL).
